daily_etl:
  sources:
    api:
      headers:
        content-type:
          - application/json
        Authorization:
          - JWT 
      data:
         username:
          - rd_dreams
         password:
          - djT6LasE
      endpoint_auth:
        - /auth
      endpoint_api:
        - /out_of_stock
    postgresql_dshop:
      - aisles
      - clients
      - departments
      - orders
      - products
